sudo: required
services:
  - docker

before_install:
  - docker build -t mattaltepeter/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mattaltepeter/react-test npm test -- --coverage

after_success:
  - docker build -t mattaltepeter/multi-client ./client
  - docker build -t mattaltepeter/multi-nginx ./nginx
  - docker build -t mattaltepeter/multi-server ./server
  - docker build -t mattaltepeter/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mattaltepeter/multi-client
  - docker push mattaltepeter/multi-nginx
  - docker push mattaltepeter/multi-server
  - docker push mattaltepeter/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-137735033005
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY